package randoop;

import junit.framework.*;

public class ClienteRest0 extends TestCase {

  public static boolean debug = false;

  public void test1() throws Throwable {

    if (debug) System.out.printf("%nClienteRest0.test1");


    com.application.ciadobusao.db.ClienteRest var0 = new com.application.ciadobusao.db.ClienteRest();
    // The following exception was thrown during execution.
    // This behavior will recorded for regression testing.
    try {
      java.util.List var2 = var0.getPerfisConfirmados("");
      fail("Expected exception of type java.lang.NoClassDefFoundError");
    } catch (java.lang.NoClassDefFoundError e) {
      // Expected exception.
    }

  }

  public void test2() throws Throwable {

    if (debug) System.out.printf("%nClienteRest0.test2");


    com.application.ciadobusao.db.ClienteRest var0 = new com.application.ciadobusao.db.ClienteRest();
    // The following exception was thrown during execution.
    // This behavior will recorded for regression testing.
    try {
      java.lang.String var3 = var0.confirmaPresenca(1, "");
      fail("Expected exception of type java.lang.NoClassDefFoundError");
    } catch (java.lang.NoClassDefFoundError e) {
      // Expected exception.
    }

  }

  public void test3() throws Throwable {

    if (debug) System.out.printf("%nClienteRest0.test3");


    com.application.ciadobusao.db.ClienteRest var0 = new com.application.ciadobusao.db.ClienteRest();
    // The following exception was thrown during execution.
    // This behavior will recorded for regression testing.
    try {
      com.application.ciadobusao.util.Encontro var2 = var0.getEncontro(100);
      fail("Expected exception of type java.lang.NoClassDefFoundError");
    } catch (java.lang.NoClassDefFoundError e) {
      // Expected exception.
    }

  }

  public void test4() throws Throwable {

    if (debug) System.out.printf("%nClienteRest0.test4");


    com.application.ciadobusao.db.ClienteRest var0 = new com.application.ciadobusao.db.ClienteRest();
    // The following exception was thrown during execution.
    // This behavior will recorded for regression testing.
    try {
      java.lang.String var3 = var0.confirmaQueChegou(1, "");
      fail("Expected exception of type java.lang.NoClassDefFoundError");
    } catch (java.lang.NoClassDefFoundError e) {
      // Expected exception.
    }

  }

  public void test5() throws Throwable {

    if (debug) System.out.printf("%nClienteRest0.test5");


    com.application.ciadobusao.db.ClienteRest var0 = new com.application.ciadobusao.db.ClienteRest();
    // The following exception was thrown during execution.
    // This behavior will recorded for regression testing.
    try {
      java.lang.String var2 = var0.deletarEncontro(10);
      fail("Expected exception of type java.lang.NoClassDefFoundError");
    } catch (java.lang.NoClassDefFoundError e) {
      // Expected exception.
    }

  }

  public void test6() throws Throwable {

    if (debug) System.out.printf("%nClienteRest0.test6");


    com.application.ciadobusao.db.ClienteRest var0 = new com.application.ciadobusao.db.ClienteRest();
    // The following exception was thrown during execution.
    // This behavior will recorded for regression testing.
    try {
      java.lang.String var3 = var0.confirmaPresenca((-1), "hi!");
      fail("Expected exception of type java.lang.NoClassDefFoundError");
    } catch (java.lang.NoClassDefFoundError e) {
      // Expected exception.
    }

  }

  public void test7() throws Throwable {

    if (debug) System.out.printf("%nClienteRest0.test7");


    com.application.ciadobusao.db.ClienteRest var0 = new com.application.ciadobusao.db.ClienteRest();
    // The following exception was thrown during execution.
    // This behavior will recorded for regression testing.
    try {
      java.util.List var2 = var0.getPerfisNaoChegaram("");
      fail("Expected exception of type java.lang.NoClassDefFoundError");
    } catch (java.lang.NoClassDefFoundError e) {
      // Expected exception.
    }

  }

  public void test8() throws Throwable {

    if (debug) System.out.printf("%nClienteRest0.test8");


    com.application.ciadobusao.db.ClienteRest var0 = new com.application.ciadobusao.db.ClienteRest();
    // The following exception was thrown during execution.
    // This behavior will recorded for regression testing.
    try {
      com.application.ciadobusao.util.Encontro var2 = var0.getEncontro(0);
      fail("Expected exception of type java.lang.NoClassDefFoundError");
    } catch (java.lang.NoClassDefFoundError e) {
      // Expected exception.
    }

  }

  public void test9() throws Throwable {

    if (debug) System.out.printf("%nClienteRest0.test9");


    com.application.ciadobusao.db.ClienteRest var0 = new com.application.ciadobusao.db.ClienteRest();
    // The following exception was thrown during execution.
    // This behavior will recorded for regression testing.
    try {
      java.lang.String var3 = var0.desconfirmarPresenca(1, "hi!");
      fail("Expected exception of type java.lang.NoClassDefFoundError");
    } catch (java.lang.NoClassDefFoundError e) {
      // Expected exception.
    }

  }

  public void test10() throws Throwable {

    if (debug) System.out.printf("%nClienteRest0.test10");


    com.application.ciadobusao.db.ClienteRest var0 = new com.application.ciadobusao.db.ClienteRest();
    // The following exception was thrown during execution.
    // This behavior will recorded for regression testing.
    try {
      java.util.List var2 = var0.getMeusEncontros("");
      fail("Expected exception of type java.lang.NoClassDefFoundError");
    } catch (java.lang.NoClassDefFoundError e) {
      // Expected exception.
    }

  }

  public void test11() throws Throwable {

    if (debug) System.out.printf("%nClienteRest0.test11");


    com.application.ciadobusao.db.ClienteRest var0 = new com.application.ciadobusao.db.ClienteRest();
    // The following exception was thrown during execution.
    // This behavior will recorded for regression testing.
    try {
      com.application.ciadobusao.util.Encontro var2 = var0.getEncontro(1);
      fail("Expected exception of type java.lang.NoClassDefFoundError");
    } catch (java.lang.NoClassDefFoundError e) {
      // Expected exception.
    }

  }

  public void test12() throws Throwable {

    if (debug) System.out.printf("%nClienteRest0.test12");


    com.application.ciadobusao.db.ClienteRest var0 = new com.application.ciadobusao.db.ClienteRest();
    // The following exception was thrown during execution.
    // This behavior will recorded for regression testing.
    try {
      java.lang.String var3 = var0.confirmaPresenca(1, "hi!");
      fail("Expected exception of type java.lang.NoClassDefFoundError");
    } catch (java.lang.NoClassDefFoundError e) {
      // Expected exception.
    }

  }

  public void test13() throws Throwable {

    if (debug) System.out.printf("%nClienteRest0.test13");


    com.application.ciadobusao.db.ClienteRest var0 = new com.application.ciadobusao.db.ClienteRest();
    // The following exception was thrown during execution.
    // This behavior will recorded for regression testing.
    try {
      java.util.List var2 = var0.getEncontrosNaoParticipo("");
      fail("Expected exception of type java.lang.NoClassDefFoundError");
    } catch (java.lang.NoClassDefFoundError e) {
      // Expected exception.
    }

  }

  public void test14() throws Throwable {

    if (debug) System.out.printf("%nClienteRest0.test14");


    com.application.ciadobusao.db.ClienteRest var0 = new com.application.ciadobusao.db.ClienteRest();
    // The following exception was thrown during execution.
    // This behavior will recorded for regression testing.
    try {
      java.util.List var2 = var0.getMeusEncontros("hi!");
      fail("Expected exception of type java.lang.NoClassDefFoundError");
    } catch (java.lang.NoClassDefFoundError e) {
      // Expected exception.
    }

  }

  public void test15() throws Throwable {

    if (debug) System.out.printf("%nClienteRest0.test15");


    com.application.ciadobusao.db.ClienteRest var0 = new com.application.ciadobusao.db.ClienteRest();
    // The following exception was thrown during execution.
    // This behavior will recorded for regression testing.
    try {
      java.util.List var2 = var0.getPerfisChegaram("hi!");
      fail("Expected exception of type java.lang.NoClassDefFoundError");
    } catch (java.lang.NoClassDefFoundError e) {
      // Expected exception.
    }

  }

  public void test16() throws Throwable {

    if (debug) System.out.printf("%nClienteRest0.test16");


    com.application.ciadobusao.db.ClienteRest var0 = new com.application.ciadobusao.db.ClienteRest();
    // The following exception was thrown during execution.
    // This behavior will recorded for regression testing.
    try {
      java.lang.String var3 = var0.confirmaQueChegou(100, "hi!");
      fail("Expected exception of type java.lang.NoClassDefFoundError");
    } catch (java.lang.NoClassDefFoundError e) {
      // Expected exception.
    }

  }

  public void test17() throws Throwable {

    if (debug) System.out.printf("%nClienteRest0.test17");


    com.application.ciadobusao.db.ClienteRest var0 = new com.application.ciadobusao.db.ClienteRest();
    // The following exception was thrown during execution.
    // This behavior will recorded for regression testing.
    try {
      java.util.List var2 = var0.getPerfisChegaram("");
      fail("Expected exception of type java.lang.NoClassDefFoundError");
    } catch (java.lang.NoClassDefFoundError e) {
      // Expected exception.
    }

  }

  public void test18() throws Throwable {

    if (debug) System.out.printf("%nClienteRest0.test18");


    com.application.ciadobusao.db.ClienteRest var0 = new com.application.ciadobusao.db.ClienteRest();
    // The following exception was thrown during execution.
    // This behavior will recorded for regression testing.
    try {
      java.lang.String var3 = var0.confirmaQueChegou(0, "hi!");
      fail("Expected exception of type java.lang.NoClassDefFoundError");
    } catch (java.lang.NoClassDefFoundError e) {
      // Expected exception.
    }

  }

  public void test19() throws Throwable {

    if (debug) System.out.printf("%nClienteRest0.test19");


    com.application.ciadobusao.db.ClienteRest var0 = new com.application.ciadobusao.db.ClienteRest();
    // The following exception was thrown during execution.
    // This behavior will recorded for regression testing.
    try {
      com.application.ciadobusao.util.Encontro var2 = var0.getEncontro(10);
      fail("Expected exception of type java.lang.NoClassDefFoundError");
    } catch (java.lang.NoClassDefFoundError e) {
      // Expected exception.
    }

  }

  public void test20() throws Throwable {

    if (debug) System.out.printf("%nClienteRest0.test20");


    com.application.ciadobusao.db.ClienteRest var0 = new com.application.ciadobusao.db.ClienteRest();
    // The following exception was thrown during execution.
    // This behavior will recorded for regression testing.
    try {
      java.util.List var1 = var0.getListaEncontro();
      fail("Expected exception of type java.lang.NoClassDefFoundError");
    } catch (java.lang.NoClassDefFoundError e) {
      // Expected exception.
    }

  }

  public void test21() throws Throwable {

    if (debug) System.out.printf("%nClienteRest0.test21");


    com.application.ciadobusao.db.ClienteRest var0 = new com.application.ciadobusao.db.ClienteRest();
    // The following exception was thrown during execution.
    // This behavior will recorded for regression testing.
    try {
      java.lang.String var3 = var0.confirmaQueChegou(10, "hi!");
      fail("Expected exception of type java.lang.NoClassDefFoundError");
    } catch (java.lang.NoClassDefFoundError e) {
      // Expected exception.
    }

  }

  public void test22() throws Throwable {

    if (debug) System.out.printf("%nClienteRest0.test22");


    com.application.ciadobusao.db.ClienteRest var0 = new com.application.ciadobusao.db.ClienteRest();
    // The following exception was thrown during execution.
    // This behavior will recorded for regression testing.
    try {
      java.util.List var2 = var0.getPerfisConfirmados("hi!");
      fail("Expected exception of type java.lang.NoClassDefFoundError");
    } catch (java.lang.NoClassDefFoundError e) {
      // Expected exception.
    }

  }

  public void test23() throws Throwable {

    if (debug) System.out.printf("%nClienteRest0.test23");


    com.application.ciadobusao.db.ClienteRest var0 = new com.application.ciadobusao.db.ClienteRest();
    // The following exception was thrown during execution.
    // This behavior will recorded for regression testing.
    try {
      java.lang.String var3 = var0.desconfirmarPresenca((-1), "");
      fail("Expected exception of type java.lang.NoClassDefFoundError");
    } catch (java.lang.NoClassDefFoundError e) {
      // Expected exception.
    }

  }

  public void test24() throws Throwable {

    if (debug) System.out.printf("%nClienteRest0.test24");


    com.application.ciadobusao.db.ClienteRest var0 = new com.application.ciadobusao.db.ClienteRest();
    // The following exception was thrown during execution.
    // This behavior will recorded for regression testing.
    try {
      java.lang.String var3 = var0.confirmaPresenca(0, "hi!");
      fail("Expected exception of type java.lang.NoClassDefFoundError");
    } catch (java.lang.NoClassDefFoundError e) {
      // Expected exception.
    }

  }

  public void test25() throws Throwable {

    if (debug) System.out.printf("%nClienteRest0.test25");


    com.application.ciadobusao.db.ClienteRest var0 = new com.application.ciadobusao.db.ClienteRest();
    // The following exception was thrown during execution.
    // This behavior will recorded for regression testing.
    try {
      java.lang.String var3 = var0.confirmaPresenca(10, "");
      fail("Expected exception of type java.lang.NoClassDefFoundError");
    } catch (java.lang.NoClassDefFoundError e) {
      // Expected exception.
    }

  }

  public void test26() throws Throwable {

    if (debug) System.out.printf("%nClienteRest0.test26");


    com.application.ciadobusao.db.ClienteRest var0 = new com.application.ciadobusao.db.ClienteRest();
    // The following exception was thrown during execution.
    // This behavior will recorded for regression testing.
    try {
      java.lang.String var2 = var0.deletarEncontro(1);
      fail("Expected exception of type java.lang.NoClassDefFoundError");
    } catch (java.lang.NoClassDefFoundError e) {
      // Expected exception.
    }

  }

  public void test27() throws Throwable {

    if (debug) System.out.printf("%nClienteRest0.test27");


    com.application.ciadobusao.db.ClienteRest var0 = new com.application.ciadobusao.db.ClienteRest();
    // The following exception was thrown during execution.
    // This behavior will recorded for regression testing.
    try {
      java.util.List var2 = var0.getPerfisNaoChegaram("hi!");
      fail("Expected exception of type java.lang.NoClassDefFoundError");
    } catch (java.lang.NoClassDefFoundError e) {
      // Expected exception.
    }

  }

  public void test28() throws Throwable {

    if (debug) System.out.printf("%nClienteRest0.test28");


    com.application.ciadobusao.db.ClienteRest var0 = new com.application.ciadobusao.db.ClienteRest();
    // The following exception was thrown during execution.
    // This behavior will recorded for regression testing.
    try {
      java.lang.String var3 = var0.desconfirmarPresenca(10, "");
      fail("Expected exception of type java.lang.NoClassDefFoundError");
    } catch (java.lang.NoClassDefFoundError e) {
      // Expected exception.
    }

  }

  public void test29() throws Throwable {

    if (debug) System.out.printf("%nClienteRest0.test29");


    com.application.ciadobusao.db.ClienteRest var0 = new com.application.ciadobusao.db.ClienteRest();
    // The following exception was thrown during execution.
    // This behavior will recorded for regression testing.
    try {
      java.lang.String var2 = var0.deletarEncontro(0);
      fail("Expected exception of type java.lang.NoClassDefFoundError");
    } catch (java.lang.NoClassDefFoundError e) {
      // Expected exception.
    }

  }

  public void test30() throws Throwable {

    if (debug) System.out.printf("%nClienteRest0.test30");


    com.application.ciadobusao.db.ClienteRest var0 = new com.application.ciadobusao.db.ClienteRest();
    // The following exception was thrown during execution.
    // This behavior will recorded for regression testing.
    try {
      java.lang.String var3 = var0.desconfirmarPresenca(100, "hi!");
      fail("Expected exception of type java.lang.NoClassDefFoundError");
    } catch (java.lang.NoClassDefFoundError e) {
      // Expected exception.
    }

  }

  public void test31() throws Throwable {

    if (debug) System.out.printf("%nClienteRest0.test31");


    com.application.ciadobusao.db.ClienteRest var0 = new com.application.ciadobusao.db.ClienteRest();
    // The following exception was thrown during execution.
    // This behavior will recorded for regression testing.
    try {
      java.lang.String var3 = var0.confirmaQueChegou(100, "");
      fail("Expected exception of type java.lang.NoClassDefFoundError");
    } catch (java.lang.NoClassDefFoundError e) {
      // Expected exception.
    }

  }

  public void test32() throws Throwable {

    if (debug) System.out.printf("%nClienteRest0.test32");


    com.application.ciadobusao.db.ClienteRest var0 = new com.application.ciadobusao.db.ClienteRest();
    // The following exception was thrown during execution.
    // This behavior will recorded for regression testing.
    try {
      java.util.List var2 = var0.getEncontrosNaoParticipo("hi!");
      fail("Expected exception of type java.lang.NoClassDefFoundError");
    } catch (java.lang.NoClassDefFoundError e) {
      // Expected exception.
    }

  }

  public void test33() throws Throwable {

    if (debug) System.out.printf("%nClienteRest0.test33");


    com.application.ciadobusao.db.ClienteRest var0 = new com.application.ciadobusao.db.ClienteRest();
    // The following exception was thrown during execution.
    // This behavior will recorded for regression testing.
    try {
      java.lang.String var3 = var0.confirmaPresenca(10, "hi!");
      fail("Expected exception of type java.lang.NoClassDefFoundError");
    } catch (java.lang.NoClassDefFoundError e) {
      // Expected exception.
    }

  }

  public void test34() throws Throwable {

    if (debug) System.out.printf("%nClienteRest0.test34");


    com.application.ciadobusao.db.ClienteRest var0 = new com.application.ciadobusao.db.ClienteRest();
    // The following exception was thrown during execution.
    // This behavior will recorded for regression testing.
    try {
      java.lang.String var3 = var0.desconfirmarPresenca(100, "");
      fail("Expected exception of type java.lang.NoClassDefFoundError");
    } catch (java.lang.NoClassDefFoundError e) {
      // Expected exception.
    }

  }

  public void test35() throws Throwable {

    if (debug) System.out.printf("%nClienteRest0.test35");


    com.application.ciadobusao.db.ClienteRest var0 = new com.application.ciadobusao.db.ClienteRest();
    // The following exception was thrown during execution.
    // This behavior will recorded for regression testing.
    try {
      java.lang.String var3 = var0.confirmaQueChegou(1, "hi!");
      fail("Expected exception of type java.lang.NoClassDefFoundError");
    } catch (java.lang.NoClassDefFoundError e) {
      // Expected exception.
    }

  }

  public void test36() throws Throwable {

    if (debug) System.out.printf("%nClienteRest0.test36");


    com.application.ciadobusao.db.ClienteRest var0 = new com.application.ciadobusao.db.ClienteRest();
    // The following exception was thrown during execution.
    // This behavior will recorded for regression testing.
    try {
      java.lang.String var2 = var0.deletarEncontro((-1));
      fail("Expected exception of type java.lang.NoClassDefFoundError");
    } catch (java.lang.NoClassDefFoundError e) {
      // Expected exception.
    }

  }

  public void test37() throws Throwable {

    if (debug) System.out.printf("%nClienteRest0.test37");


    com.application.ciadobusao.db.ClienteRest var0 = new com.application.ciadobusao.db.ClienteRest();
    // The following exception was thrown during execution.
    // This behavior will recorded for regression testing.
    try {
      java.lang.String var3 = var0.confirmaQueChegou((-1), "hi!");
      fail("Expected exception of type java.lang.NoClassDefFoundError");
    } catch (java.lang.NoClassDefFoundError e) {
      // Expected exception.
    }

  }

  public void test38() throws Throwable {

    if (debug) System.out.printf("%nClienteRest0.test38");


    com.application.ciadobusao.db.ClienteRest var0 = new com.application.ciadobusao.db.ClienteRest();
    // The following exception was thrown during execution.
    // This behavior will recorded for regression testing.
    try {
      com.application.ciadobusao.util.Encontro var2 = var0.getEncontro((-1));
      fail("Expected exception of type java.lang.NoClassDefFoundError");
    } catch (java.lang.NoClassDefFoundError e) {
      // Expected exception.
    }

  }

  public void test39() throws Throwable {

    if (debug) System.out.printf("%nClienteRest0.test39");


    com.application.ciadobusao.db.ClienteRest var0 = new com.application.ciadobusao.db.ClienteRest();
    // The following exception was thrown during execution.
    // This behavior will recorded for regression testing.
    try {
      java.lang.String var3 = var0.confirmaQueChegou((-1), "");
      fail("Expected exception of type java.lang.NoClassDefFoundError");
    } catch (java.lang.NoClassDefFoundError e) {
      // Expected exception.
    }

  }

  public void test40() throws Throwable {

    if (debug) System.out.printf("%nClienteRest0.test40");


    com.application.ciadobusao.db.ClienteRest var0 = new com.application.ciadobusao.db.ClienteRest();
    // The following exception was thrown during execution.
    // This behavior will recorded for regression testing.
    try {
      java.lang.String var3 = var0.confirmaPresenca(0, "");
      fail("Expected exception of type java.lang.NoClassDefFoundError");
    } catch (java.lang.NoClassDefFoundError e) {
      // Expected exception.
    }

  }

  public void test41() throws Throwable {

    if (debug) System.out.printf("%nClienteRest0.test41");


    com.application.ciadobusao.db.ClienteRest var0 = new com.application.ciadobusao.db.ClienteRest();
    // The following exception was thrown during execution.
    // This behavior will recorded for regression testing.
    try {
      java.lang.String var3 = var0.confirmaPresenca(100, "hi!");
      fail("Expected exception of type java.lang.NoClassDefFoundError");
    } catch (java.lang.NoClassDefFoundError e) {
      // Expected exception.
    }

  }

  public void test42() throws Throwable {

    if (debug) System.out.printf("%nClienteRest0.test42");


    com.application.ciadobusao.db.ClienteRest var0 = new com.application.ciadobusao.db.ClienteRest();
    // The following exception was thrown during execution.
    // This behavior will recorded for regression testing.
    try {
      java.lang.String var3 = var0.desconfirmarPresenca(10, "hi!");
      fail("Expected exception of type java.lang.NoClassDefFoundError");
    } catch (java.lang.NoClassDefFoundError e) {
      // Expected exception.
    }

  }

  public void test43() throws Throwable {

    if (debug) System.out.printf("%nClienteRest0.test43");


    com.application.ciadobusao.db.ClienteRest var0 = new com.application.ciadobusao.db.ClienteRest();
    // The following exception was thrown during execution.
    // This behavior will recorded for regression testing.
    try {
      java.lang.String var3 = var0.confirmaPresenca(100, "");
      fail("Expected exception of type java.lang.NoClassDefFoundError");
    } catch (java.lang.NoClassDefFoundError e) {
      // Expected exception.
    }

  }

  public void test44() throws Throwable {

    if (debug) System.out.printf("%nClienteRest0.test44");


    com.application.ciadobusao.db.ClienteRest var0 = new com.application.ciadobusao.db.ClienteRest();
    // The following exception was thrown during execution.
    // This behavior will recorded for regression testing.
    try {
      java.lang.String var3 = var0.confirmaQueChegou(10, "");
      fail("Expected exception of type java.lang.NoClassDefFoundError");
    } catch (java.lang.NoClassDefFoundError e) {
      // Expected exception.
    }

  }

  public void test45() throws Throwable {

    if (debug) System.out.printf("%nClienteRest0.test45");


    com.application.ciadobusao.db.ClienteRest var0 = new com.application.ciadobusao.db.ClienteRest();
    // The following exception was thrown during execution.
    // This behavior will recorded for regression testing.
    try {
      java.lang.String var2 = var0.deletarEncontro(100);
      fail("Expected exception of type java.lang.NoClassDefFoundError");
    } catch (java.lang.NoClassDefFoundError e) {
      // Expected exception.
    }

  }

  public void test46() throws Throwable {

    if (debug) System.out.printf("%nClienteRest0.test46");


    com.application.ciadobusao.db.ClienteRest var0 = new com.application.ciadobusao.db.ClienteRest();
    // The following exception was thrown during execution.
    // This behavior will recorded for regression testing.
    try {
      java.lang.String var3 = var0.desconfirmarPresenca(1, "");
      fail("Expected exception of type java.lang.NoClassDefFoundError");
    } catch (java.lang.NoClassDefFoundError e) {
      // Expected exception.
    }

  }

  public void test47() throws Throwable {

    if (debug) System.out.printf("%nClienteRest0.test47");


    com.application.ciadobusao.db.ClienteRest var0 = new com.application.ciadobusao.db.ClienteRest();
    // The following exception was thrown during execution.
    // This behavior will recorded for regression testing.
    try {
      java.lang.String var3 = var0.desconfirmarPresenca(0, "hi!");
      fail("Expected exception of type java.lang.NoClassDefFoundError");
    } catch (java.lang.NoClassDefFoundError e) {
      // Expected exception.
    }

  }

  public void test48() throws Throwable {

    if (debug) System.out.printf("%nClienteRest0.test48");


    com.application.ciadobusao.db.ClienteRest var0 = new com.application.ciadobusao.db.ClienteRest();
    // The following exception was thrown during execution.
    // This behavior will recorded for regression testing.
    try {
      java.lang.String var3 = var0.confirmaPresenca((-1), "");
      fail("Expected exception of type java.lang.NoClassDefFoundError");
    } catch (java.lang.NoClassDefFoundError e) {
      // Expected exception.
    }

  }

  public void test49() throws Throwable {

    if (debug) System.out.printf("%nClienteRest0.test49");


    com.application.ciadobusao.db.ClienteRest var0 = new com.application.ciadobusao.db.ClienteRest();
    // The following exception was thrown during execution.
    // This behavior will recorded for regression testing.
    try {
      java.lang.String var3 = var0.desconfirmarPresenca(0, "");
      fail("Expected exception of type java.lang.NoClassDefFoundError");
    } catch (java.lang.NoClassDefFoundError e) {
      // Expected exception.
    }

  }

  public void test50() throws Throwable {

    if (debug) System.out.printf("%nClienteRest0.test50");


    com.application.ciadobusao.db.ClienteRest var0 = new com.application.ciadobusao.db.ClienteRest();
    // The following exception was thrown during execution.
    // This behavior will recorded for regression testing.
    try {
      java.lang.String var3 = var0.confirmaQueChegou(0, "");
      fail("Expected exception of type java.lang.NoClassDefFoundError");
    } catch (java.lang.NoClassDefFoundError e) {
      // Expected exception.
    }

  }

  public void test51() throws Throwable {

    if (debug) System.out.printf("%nClienteRest0.test51");


    com.application.ciadobusao.db.ClienteRest var0 = new com.application.ciadobusao.db.ClienteRest();
    // The following exception was thrown during execution.
    // This behavior will recorded for regression testing.
    try {
      java.lang.String var3 = var0.desconfirmarPresenca((-1), "hi!");
      fail("Expected exception of type java.lang.NoClassDefFoundError");
    } catch (java.lang.NoClassDefFoundError e) {
      // Expected exception.
    }

  }

}
